[이가은] 1주차 미션 제출
DKU-D-Coding/react-study-carrot-market pull request #7
Opened 2023-01-21 10:46 UTC by gaeunnlee

Home과 Product 페이지 구현 완료하였습니다! ([링크](https://react-study-carrot-market.vercel.app/product/409))

2023-01-22 00:10 UTC, ho991217 commented on react_project/src/Components/Home/Card.js
> +                    <img src={props.img}/>
이미지 사이즈가 너무 큽니다! 피그마 보시면 대략 120x120 픽셀로 되어있는데 거의 200x200으로 나오네요!
<img width="391" alt="스크린샷 2023-01-22 09 08 16" src="https://user-images.githubusercontent.com/84632077/213894918-bc03ab36-78a1-4ec6-8fec-37348c108785.png">
위쪽이 제가 조절 한 모습이고, 아래가 가은님이 만들어 주신 모습입니다.

2023-01-22 01:31 UTC, ho991217 requested changes

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Home/Card.js
> +const CardBox = styled.div`
전반적인 사이즈가 너무 큰 것 같습니다!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Home/Card.js
> +                    <img src={props.img}/>
이미지 사이즈가 너무 큽니다! 피그마 보시면 대략 120x120 픽셀로 되어있는데 거의 200x200으로 나오네요!
<img width="391" alt="스크린샷 2023-01-22 09 08 16" src="https://user-images.githubusercontent.com/84632077/213894918-bc03ab36-78a1-4ec6-8fec-37348c108785.png">
위쪽이 제가 조절 한 모습이고, 아래가 가은님이 만들어 주신 모습입니다.

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/UserGoods.js
> +                <UserCard img={process.env.PUBLIC_URL + '/no_img.jpg'} title="제목" price="가격" goodsId="226"/>
이렇게 복수의 컴포넌트를 사용할 때에는 매핑을 활용하면 좋습니다! 실제 서비스에서는 api 통신을 통해 받은 데이터를 뿌려줍니다! 비슷한 원리로 만들어주시면 좋을 것 같아요!
```javascript
cards = [
   {
      imgSrc: baseUrl + 'no_img.jpg',
      title: "제목 1",
      price: "가격 1",
      goodsId: "226",
   },
   {
      imgSrc: baseUrl + 'no_img.jpg',
      title: "제목 2",
      price: "가격 2",
      goodsId: "227",
   },
   ...
]
...
   return (
      <div>
         {cards.map((props) => (
            <UserCard {...props} />
         ))}
      </div>
   )
}



```

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/UserCard.js
> +function UserCard(props){
구조파괴식으로 받아오시면 ```props.``` 을 써 줄 필요가 없습니다!
```javascript
function UserCard({ goodsId, img, title, price }) ...
```

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/UserCard.js
> +                <img src={props.img}/>
속성 이름이 ```img```라면, ```<img />``` 태그와 간섭이 생길 수 있습니다! ```imgSrc```와 같은 이름을 고려 해 보면 좋을 것 같네요

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/App.js
> +      <div className="App">
이 ```<div> </div>```는 불필요 해 보이네요!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/ProductBottomBar.js
> +            |
```border-right: 1px solid black;```같은걸 활용하는 것도 좋아보이네요!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/ProductTopBar.js
> +    let navigate = useNavigate();
변경 되지 않는 값은 
```javascript
const
```
로 선언 해 주세요!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/pages/Home.js
> +            <Card title="상품명" img={process.env.PUBLIC_URL + '/no_img.jpg'} alt="image" price="0" like="n" goodsId="406"/>
마찬가지로 매핑을 활용하면 좋을 것 같아보이는 부분이네요!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/pages/Product.js
> +              <CarouselItem>
캐러셀도 매핑을 이용해서 훨씬 간결한 코드로 정리할 수 있을 것 같습니다!

2023-01-22 01:31 UTC, ho991217 commented on react_project/src/Components/Product/UserGoods.js
> +
리액트에서 ```.env```를 사용하실 때에는 변수명이 반드시 ```REACT_APP_```으로 시작해야 합니다!
또한, 자주 쓰이는 상수는 최상단에 선언 해 두고 쓰시면 편합니다!
```javascript
const baseUrl = env.process.REACT_APP_PUBLIC_URL;
```
```.env```파일 안에서도 REACT_APP_으로 시작하도록 선언 해 주셔야합니다!

2023-01-24 02:28 UTC, gaeunnlee commented on react_project/src/Components/Product/UserGoods.js
> +
이 부분은 많이 서치해봤는데 적용되지 않아서 수정하지 못하였습니다!ㅠㅠ 다른 부분은 다시 수정해서 커밋했어요! 꼼꼼하게 봐주셔서 감사합니다!

2023-01-24 04:32 UTC, ho991217 commented
node_modules가 커밋되어서 파일을 모두 확인할 수가 없네요! .gitignore에 node_module 폴더를 추가 해 주세요

2023-01-24 05:53 UTC, gaeunnlee commented
아 제가 프로젝트의 상위폴더에 패키지를 잘못 설치해서 node_modules 폴더가 생긴 것 같은데 그게 커밋에 다 올라갔네요ㅠㅠ 일단
삭제했습니다!

2023년 1월 24일 (화) 오후 1:32, 이호연 ***@***.***>님이 작성:

> node_modules가 커밋되어서 파일을 모두 확인할 수가 없네요! .gitignore에 node_module 폴더를 추가 해 주세요
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DKU-D-Coding/react-study-carrot-market/pull/7#issuecomment-1401384420>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVFLI7NAMMTACMIDWK2F7S3WT5LPNANCNFSM6AAAAAAUCKTZJE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-24 06:07 UTC, ho991217 approved these changes

2023-01-24 06:07 UTC, ho991217 commented
수고 하셨습니다!

2023-01-24 08:42 UTC, gaeunnlee commented
감사합니다!!🥹🥺

2023년 1월 24일 (화) 15:07, 이호연 ***@***.***>님이 작성:

> 수고 하셨습니다!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DKU-D-Coding/react-study-carrot-market/pull/7#issuecomment-1401437721>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVFLI7POBNKJWWBV3EEBNX3WT5WTPANCNFSM6AAAAAAUCKTZJE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-26 05:47 UTC, chchaeun commented
0주차 과제 Merge하면서 conflict가 발생한 것 같습니다. 이부분 수정한 뒤 Merge 부탁드려요~

2023-01-26 06:08 UTC, gaeunnlee commented
> 0주차 과제 Merge하면서 conflict가 발생한 것 같습니다. 이부분 수정한 뒤 Merge 부탁드려요~

해결했습니다! 확인 부탁드려요!

2023-01-26 06:19 UTC, chchaeun commented
앞으로는 리뷰 받고 셀프 머지 하시면 됩니다 :) 고생했어요~~

2023-01-26 06:19 UTC, merged

2023-01-26 06:21 UTC, gaeunnlee commented
> 앞으로는 리뷰 받고 셀프 머지 하시면 됩니다 :) 고생했어요~~

넵 감사합니다!!😊